#!/bin/bash
# Script simulador de borrar (barch) basado en el documento adjunto

if test $# -eq 0
then
    echo "Uso: ./barch.sh [-t | -c] [nom_arch]"
else
    # Caso 1: Solo archivo (comprueba protección)
    if test $# -eq 1
    then
        if test -f $1
        then
            if test -r $1
            then
                rm $1
                echo "Archivo $1 borrado."
            else
                # Manejo de archivo protegido
                echo "El archivo $1 está protegido"
                echo "Desea quitar protección para borrarlo (y/n): "
                read var
                case $var in
                    y) chmod 777 $1
                       rm $1
                       echo "Protección removida y archivo borrado."
                    ;;
                    n) echo "$1 no se borrará"
                    ;;
                esac
            fi
        else
            echo "No es un archivo: $1"
            echo "Presione una tecla ... "
            read enter1
        fi
    else
        # Caso 2: Se pasan opciones (-t o -c)
        if test $# -eq 2
        then
            if test -f $2
            then
                case $1 in
                    -t) rm -f $2
                        echo "Archivo borrado directamente (-t)"
                    ;;
                    -c) echo "Desea Borrar el archivo (y/n): "
                        read va
                        # Sintaxis de IF corregida para Bash
                        if [ "$va" = "y" ]; then
                            rm -f $2
                            echo "Archivo Borrado"
                        else
                            echo "Cancelado."
                        fi
                    ;;
                    *) echo "Opción no reconocida. Use -t o -c"
                    ;;
                esac
            else
                echo "El archivo $2 no existe o no es un archivo"
                read enter1
            fi
        else
            echo "Demasiados Parámetros"
            read enter1
        fi
    fi
fi
